# Use uma imagem Official do Python
FROM python:rc-slim

# Definindo o diretório onde a aplicação será armanezada
WORKDIR /app

# Copiar os arquivos da pasta local para dentro do container
COPY . /app

# Instalar as dependências de Python de acrodo com oq foi desenvolvido
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Garante que será iniciado a aplicação
CMD ["gunicorn", "app:app"]